### PR TITLE
Fixed issues when workMinutes, workSeconds, breakMinutes or breakSeco…

### PR DESCRIPTION
**Pull request by bbqnvd**
Fixed issue #198 
In the currentTask function, before defining the minutes and seconds, I added a few if loops to cover the cases where any of work minutes, work seconds, break minutes, or break seconds is empty. When they are empty, I assumed that they are 0. Also in timerFormat of TimerSection, I cover the case where one of the minutes or seconds is empty.

### CODE REVIEW

**Comment by bbqnvd** [comment]
Fixed issue 198 at
https://github.com/SoftEng701-Group5/assignment1/issues/198

**Comment by raymondhonsumchiu** [comment]
You should probably describe the pull request a bit more e.g. Adding a issue description and how you solved the problem. Additionally, it would probably be best to not change the package-lock.json if you haven't added any new dependencies, that should be left to another PR.

**Review by raymondhonsumchiu — COMMENTED** [review]
I think you accidentally deleted the entire package-lock.json (which is a necessary file) instead of reverting your changes. Don't worry too much, I made the same mistake haha, If I were you, I would:
1. revert this deletion commit
2. copy and paste an old version of the package-lock.json and commit that.

**Comment by bbqnvd** [comment]
> I think you accidentally deleted the entire package-lock.json (which is a necessary file) instead of reverting your changes. Don't worry too much, I made the same mistake haha, If I were you, I would:
> 
> 1. revert this deletion commit
> 2. copy and paste an old version of the package-lock.json and commit that.

Hi Raymond, thanks for pointing this out. Sorry for the silly mistakes QAQ I will now revert both files to the old version of them.

**Review by raymondhonsumchiu — APPROVED** [review]
Good stuff!

**Review by mikeFam — APPROVED** [review]
Looks great, I don't have anything else to add, @raymondhonsumchiu pointed out most issues and they have been solved.

**Pull request merged**
