### PR TITLE
Enforced and Enabled Prettier Styling Checks

### PR DESCRIPTION
**Pull request by lucas2005gao**
I thought the prettier is being run as a part of the linting check workflow, but turns out it doesn't. This PR enforces prettier styling to be used and adds the functionality of running prettier across files when doing `npm run lint:fix`

### CODE REVIEW

**Review by thakurtushar02 — COMMENTED** [review]
I thought we were using single quotes instead of double for strings?

**Comment by lucas2005gao** [comment]
> I thought we were using single quotes instead of double for strings?

Uh, okay, as long as it's consistent across different files. Do I change it to the single quote as a rule then?

**Comment by lucas2005gao** [comment]
sorry boys for the ugly as PR

**Review by dongmeilim — APPROVED** [review]
Wow, that is a lot of formatting! LGTM

**Review by DanielDowling999 — APPROVED** [review]
It all looks good to me!

**Pull request merged**
