### PR TITLE
End-to-End Testing

### LINKED ISSUE #37: End-to-End Testing
As part of our CI/CD, we need to include some form of end-to-end testing. This will be done using Cypress and integrated into our git actions.

A limitation that might pop up is needing to access the firebase database to log-in, which may cause issues due to the limited amount of accesses our database can have. Will also look into ways to get around this limitation.

### PR DESCRIPTION
**Pull request by DanielDowling999**
Adds end-to-end testing for the majority of the app, testing it in a way that users would. Also adds adjusts RTL tests to focus on components, deleting some unnecessary ones and adding a new test for the DateTime. Finally, it integrates the End-to-End Testing into the pipeline, automatically running the tests.

Taskboard is not covered by these tests yet, but an issue has been made for it.

Closes #37

### CODE REVIEW

**Review by thakurtushar02 — CHANGES_REQUESTED** [review]
Can you create a new branch from your updated main in your forked repo so we can have a more accurate commit history for this PR?

**Comment by DanielDowling999** [comment]
> Can you create a new branch from your updated main in your forked repo so we can have a more accurate commit history for this PR?

Hey Tushar, I've made a branch on my forked repo called 'feature-testing'. Is that what you were looking for?

**Comment by thakurtushar02** [comment]
> > Can you create a new branch from your updated main in your forked repo so we can have a more accurate commit history for this PR?
> 
> Hey Tushar, I've made a branch on my forked repo called 'feature-testing'. Is that what you were looking for?

Nah, see how there's a lot of commits here that are irrelevant? You need to update your main to the shared repo's main, create a new branch, and put your changes there

**Comment by lucas2005gao** [comment]
It would be good if you can clean up the commit history. I can help you with that sometime today, just lmk. This is a massive pull request, so in the future let's try to break these PRs down, for example, a setup PR, then an end to end test PR, then a refactoring PR if any.

**Pull request closed without merging**
