### PR TITLE
Reset forgotten password

### LINKED ISSUE #16: Reset forgotten password
Allow a user to reset their password if they've forgotten it

Depends on #14

### PR DESCRIPTION
**Pull request by LincRui**
**Describe the issue**
#16 

**Describe the solution**
Added the function of changing the password in the login interface.

### CODE REVIEW

**Review by ggao007 — APPROVED** [review]
Looks good to me

**Review by jonathan-thamrin — COMMENTED** [review]
Implementation works well, passed manual testing. One small suggestion is to use a separate form instead of the login one when prompting for the user's email address. Other than that, everything looks great :) (May need to address the errors in the checks before merging as well.)

**Review by Denijar — CHANGES_REQUESTED** [review]
These changes have been done on a branch in the main repository, rather than on your forked repo. This is a problem and means the PR can't be merged :(. Please fork the repo, make a branch and put the changes there instead.

Also - to pass the linting checks, you can add the following to `rules` in the `.eslintrc.js` file: `'no-console': 'off',`. I think this would be an acceptable rule change because you are intending to use alerts as part of the implementation.

**Comment by LincRui** [comment]
@jonathan-thamrin Indeed, your proposal is great. I have considered it before, but time is a bit tight now. I will definitely make it perfect when I have time. Thanks.

@Denijar I have added it to the rules, do I need to submit another pr for it or how to operate now. The first time using Github, still learning. Thanks.

**Comment by Denijar** [comment]
Hey sorry my bad (I copied pasted that rule exception and didn't change it). I should be `'no-alert': 'off',` (instead of no-console). If you make that change then hopeefullyyy the checks will pass.

**Comment by Denijar** [comment]
Okay cool that has fixed some of the tests - but the rest are actually test failures, so you will need to change the test files to make them pass :)

**Comment by LincRui** [comment]
@Denijar Thanks for helping me. By the way, I am not sure about the reasons for those two unpassed. Could you plz teach me a bit?

**Comment by Denijar** [comment]
The tests are failing because initially on the login page there was only one link to click, now there are two (because you have added a reset password link). You need to edit line 26 in `App.E2ETests.js` to be `cy.get("a:first").should("contain", "Sign").click();`. This will tell cypress more clearly that it should click on the first link on the page to load the signup page.
`

**Comment by Denijar** [comment]
omg so close. I fixed the merge conflicts that popped up after another PR was merged - but now `authService.js` needs to have prettier run on it to fix the formatting, then this PR should be good to merge (don't worry about forking, I don't think that matters as much for this assignment). Do you have prettier setup to do that formatting?

**Comment by LincRui** [comment]
Well, I don't have that. Let me study how to use it.

**Comment by Denijar** [comment]
You just need to install the Prettier extension on vscode, then when you have `authService.js` open, go `ctrl + shift + P` and run "format document" - then select prettier as the formatter. Alternatively, I can fix it for you and commit to this branch if you don't mind me doing that to save time :)

**Comment by LincRui** [comment]
Thank you very much for your help. Not that I mind, I just don't want to trouble you all the time. You have helped me point out the problem. If I ask you to do it, I think it's a bit too much. : )

**Review by Denijar — APPROVED** [review]
yaay all green! Looks good - ready to merge :)

**Pull request merged**
